### ISSUE TITLE
New test MaxOnFilteredSet failing

### ISSUE THREAD

**Issue by mikebeaton** [FransBouma/Massive#274] opened 2017-01-13 16:48 UTC
Hi, sincere apologies if I've made a mistake in understanding what to check out, or what to expect, but it seems that the newly committed test `MaxOnFilteredSet` fails against the currently committed version of `Massive.Shared.cs`.

The test generates a `SqlException` with `Message` equal to `"Incorrect syntax near the keyword 'where'."`

On debugging the test, line 841 of `Massive.Shared.cs` generates `whereClauseFragment` with value `" WHERE  where = @0"`, at this point `wherePredicates` contains one string `" where = @0"` and `whereArguments` contains one string `"SalesOrderID<100000"`.

This looks to me as if the currently committed version of `TryInvokeMember` does not fully support the calling syntax used in the new test, which in turn was making me wonder if there's a pending commit to `Massive.Shared.cs` which needs to go up? But that's speculative and again, sincere apologies if I am misunderstanding what should be going on here.

**Comment by FransBouma** [comment] 2017-01-13 20:31
Odd! I ran all the tests prior to committing the latest update. Will try tomorrow to see if I can reproduce it.

**Comment by FransBouma** [comment] 2017-01-14 12:50
Hmm. It indeed fails. I ran the write tests before the last commit. I'll see why this is and fix it.

**Comment by FransBouma** [comment] 2017-01-14 13:10
Fixed. I also added a second test to illustrate how the where clause can be used differently, i.e. by a name=value pair. The where clause in the dyn. invoke method can only deal with name=value, not name < value, if you want that, you have to specify the actual where clause like with the first test (which failed, and now works). No idea what went wrong there. I think I accidentally added a test, forgot all about it, then accidentally committed it due to a merge of a PR. Anyway, it all works now :) (so the test passes now)

**Closed as completed by FransBouma** 2017-01-14 13:10 UTC
